In [2]:
import pandas as pd
import geopandas as gpd
import os

In [3]:
os.chdir('/Users/lacm/Documents/Stanford/*Capstone Research/Deliverables')

In [4]:
wide = pd.read_csv('Full Segregation Index.csv', header=0)
wide['geoleaid'] = wide['geoleaid'].astype(str)
wide.loc[wide['geoleaid'].str.len() == 6, 'geoleaid'] = '0' + wide['geoleaid']

In [5]:
wide = wide[['geoleaid', 'n_attendancezones00', 'n_attendancezones10', 'n_attendancezones11', 'n_attendancezones12',
            'n_attendancezones14', 'n_attendancezones16']]

In [6]:
wide.loc[(wide.n_1z_yrs != wide.n_yrs) & (wide.n_1z_yrs != 0)][0:50]

AttributeError: 'DataFrame' object has no attribute 'n_1z_yrs'

In [7]:
# add number of years districts have 1 attendance zone
wide['n_1z_yrs'] = 0
wide.loc[wide.n_attendancezones00 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1
wide.loc[wide.n_attendancezones10 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1
wide.loc[wide.n_attendancezones11 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1
wide.loc[wide.n_attendancezones12 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1
wide.loc[wide.n_attendancezones14 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1
wide.loc[wide.n_attendancezones16 == 1, 'n_1z_yrs'] = wide['n_1z_yrs'] + 1

In [8]:
# add number of years districts in dataset
wide['n_yrs'] = 0
wide.loc[pd.notna(wide.n_attendancezones00), 'n_yrs'] = wide['n_yrs'] + 1
wide.loc[pd.notna(wide.n_attendancezones10), 'n_yrs'] = wide['n_yrs'] + 1
wide.loc[pd.notna(wide.n_attendancezones11), 'n_yrs'] = wide['n_yrs'] + 1
wide.loc[pd.notna(wide.n_attendancezones12), 'n_yrs'] = wide['n_yrs'] + 1
wide.loc[pd.notna(wide.n_attendancezones14), 'n_yrs'] = wide['n_yrs'] + 1
wide.loc[pd.notna(wide.n_attendancezones16), 'n_yrs'] = wide['n_yrs'] + 1

In [9]:
# classify districts as either having 1 attendance zone or > 1 attendance zone
wide['az_count'] = '1'
wide.loc[(wide.n_1z_yrs == 0) | (wide.n_1z_yrs / wide.n_yrs <= 0.5), 'az_count'] = '> 1'

In [10]:
wide['az_count'].value_counts()

1      8127
> 1    4349
Name: az_count, dtype: int64

In [13]:
4349/12476*100

34.858929143956395

In [54]:
# import shapefile of us districts
district_map = gpd.read_file('/Users/lacm/Documents/Stanford/*Capstone Research/Data/SY 2015-16/School Districts (NCES)/schooldistrict_sy1516_tl17.shp')

In [60]:
district_map.to_file('attendance zone count mapping.shp',
                       driver='ESRI Shapefile')

/var/folders/f_/y82bl01510z6_6b9mz3cg6br0000gn/T/ipykernel_41092/3124195192.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  district_map.to_file('attendance zone count mapping.shp',

In [57]:
district_map

,STATEFP,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,...,geoleaid_y,n_attendancezones00,n_attendancezones10,n_attendancezones11,n_attendancezones12,n_attendancezones14,n_attendancezones16,n_1z_yrs,n_yrs,az_count
0,04,0400082,Colorado River Union High School District,00,09,12,G5410,None,E,2.711174e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04,0400450,Agua Fria Union High School District,00,09,12,G5410,None,E,2.446409e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,04,0400720,Antelope Union High School District,00,09,12,G5410,None,E,7.937908e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04,0401160,Bicentennial Union High School District,00,09,12,G5410,None,E,9.842287e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04,0401410,Buckeye Union High School District,00,09,12,G5410,None,E,3.167017e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13347,60,6000030,American Samoa Department of Education,00,PK,12,G5420,None,E,1.977591e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13348,66,6600040,Guam Department of Education,00,PK,12,G5420,None,E,5.435583e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13349,69,6900030,Commonwealth of the Northern Mariana Islands P...,00,PK,12,G5420,None,E,4.722844e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13350,72,7200030,Puerto Rico Department of Education,00,PK,12,G5420,None,E,8.868735e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13351,78,7800030,Virgin Islands Department of Education,00,PK,12,G5420,None,E,3.480137e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
district_map['az_count'].value_counts()

1      7766
> 1    4299
Name: az_count, dtype: int64

In [56]:
# merge district map with az count data
district_map = pd.merge(district_map, wide, how='left', left_on='GEOID', right_on='geoleaid')